package DistributedFileApp;

/**
* DistributedFileApp/DistributedFileHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFile.idl
* Wednesday, December 2, 2020 12:23:49 AM EST
*/

public final class DistributedFileHolder implements org.omg.CORBA.portable.Streamable
{
  public DistributedFileApp.DistributedFile value = null;

  public DistributedFileHolder ()
  {
  }

  public DistributedFileHolder (DistributedFileApp.DistributedFile initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = DistributedFileApp.DistributedFileHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    DistributedFileApp.DistributedFileHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return DistributedFileApp.DistributedFileHelper.type ();
  }

}
