package DistributedFileApp;


/**
* DistributedFileApp/DistributedFile.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFile.idl
* Wednesday, December 2, 2020 12:23:49 AM EST
*/

public interface DistributedFile extends DistributedFileOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DistributedFile
