package DistributedFileApp;


/**
* DistributedFileApp/DistributedFileOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFile.idl
* Wednesday, December 2, 2020 12:23:49 AM EST
*/

public interface DistributedFileOperations 
{
  String csOpenRead (String fileName);
  boolean csCloseRead (String fileName);
  String csOpenWrite (String fileName);
  boolean csCloseWrite (String fileName);
  String ssOpenRead (String fileName);
  boolean ssCloseRead (String fileName);
  String ssOpenWrite (String fileName);
  boolean ssLockWrite (String fileName);
  String ssCloseWrite (String fileName);
  void shutdown ();
} // interface DistributedFileOperations
