package DistributedFileApp;


/**
* DistributedFileApp/DistributedFileHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from DistributedFile.idl
* Wednesday, December 2, 2020 12:23:49 AM EST
*/

abstract public class DistributedFileHelper
{
  private static String  _id = "IDL:DistributedFileApp/DistributedFile:1.0";

  public static void insert (org.omg.CORBA.Any a, DistributedFileApp.DistributedFile that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static DistributedFileApp.DistributedFile extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (DistributedFileApp.DistributedFileHelper.id (), "DistributedFile");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static DistributedFileApp.DistributedFile read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DistributedFileStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, DistributedFileApp.DistributedFile value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static DistributedFileApp.DistributedFile narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DistributedFileApp.DistributedFile)
      return (DistributedFileApp.DistributedFile)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DistributedFileApp._DistributedFileStub stub = new DistributedFileApp._DistributedFileStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static DistributedFileApp.DistributedFile unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof DistributedFileApp.DistributedFile)
      return (DistributedFileApp.DistributedFile)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      DistributedFileApp._DistributedFileStub stub = new DistributedFileApp._DistributedFileStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
